### ISSUE TITLE
SmartChartDouble doesn't have a save button

### ISSUE THREAD

**Issue by briansemrau** [Nashoba-Robotics/SmartChart#1]
The readme for SmartChartDouble says you can save to .csv but you can't.

**Comment by gbear605** [comment]
Ah, it shouldn't have that in the README, since we never got around to implementing it.

**Comment by gbear605** [comment]
This is fixed by https://github.com/Nashoba-Robotics/SmartChart/commit/9f73c84d202a449002125d634b2c5aa24cb8580f, but is untested. If you experience any issues, let me know. I'm updating the Releases now.

**Comment by gbear605** [comment]
Releases is now updated.

**Comment by briansemrau** [comment]
I'll test it out when I get the chance, thanks

**Comment by briansemrau** [comment]
Tried it a while ago, it works
